development:
  clients:
    default:
      database: onboarding_fcm_local_db
      hosts:
        - localhost:27017

  options:
    raise_not_found_error: false
    use_activesupport_time_zone: true
    use_utc: false

        
  
